# User-specific configuration; adjust according to hardware capabilities and preferences

# Optimize speed by loading the entire model into memory (requires ~5GB RAM)
use_mmap = true

# Utilize CPU threads; set to 0 to prioritize GPU usage over CPU
n_threads = 6

# Utilize GPU layers for faster processing with a strong GPU
n_gpu_layers = 33

# Ensure deterministic model outputs by specifying a seed
seed = -1

# Toggle verbose logging of model configurations
verbose = false

f16_kv = true

use_mlock = true

n_context = 1500

n_batch = 512

rope_freq_base = 0

rope_freq_scale = 0

max_tokens = 5000

stop = ["</s>", "<|EOT|>", "Instruction:"]

min_p = 0.1

temperature = 0.2

repeat_penalty = 1.1
